groups:
  - name: devs # name of the group
    internal_reviewers: 1 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
#      - guiburato
#      - coltborg
      - enyia21
#      - sree-cfa
