spring:
  thymeleaf:
    cache: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/postgres
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
form-flow:
  error:
    show-stack-trace: false
  virus-scanning:
    enabled: true
  short-code:
    short-code-configs:
      gcc:
        prefix: QA-
        creation-point: creation
  uploads:
    max-file-size: ${UPLOADS_MAX_FILE_SIZE:10}
    file-conversion:
      max-conversion-size: ${UPLOADS_MAX_CONVERSION_SIZE:10}
      max-pages: ${UPLOADS_MAX_PAGES:50}
  validation:
    ssn-pattern: "\\d{3}-\\d{2}-\\d{4}"
  aws:
    region: ${AWS_REGION}
    s3_bucket_name: ${AWS_BUCKET}
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
il-gcc:
  enable-emails: ${ENABLE_EMAILS_FLAG:true}
  dts:
    processing-org: '4c-ccap-apps-testing'
