
ALTER TABLE submissions
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
  USING created_at AT TIME ZONE 'UTC';

ALTER TABLE submissions
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE
  USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE submissions
ALTER COLUMN submitted_at TYPE TIMESTAMP WITH TIME ZONE
  USING submitted_at AT TIME ZONE 'UTC';