name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy (e.g. v1.2.3 or hotfix/my-branch)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo with all tags and branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify ref exists
        run: |
          if git show-ref --verify --quiet refs/tags/${{ github.event.inputs.ref }}; then
            echo "Found tag ${{ github.event.inputs.ref }}"
          elif git show-ref --verify --quiet refs/heads/${{ github.event.inputs.ref }}; then
            echo "Found branch ${{ github.event.inputs.ref }}"
          else
            echo "ERROR: Ref '${{ github.event.inputs.ref }}' not found as a tag or branch."
            exit 1
          fi

      - name: Checkout the requested ref
        run: |
          git checkout ${{ github.event.inputs.ref }}

      - name: Show commit being deployed
        run: |
          echo "Deploying commit:"
          git log -1 --oneline
          echo "Ref type:"
          git describe --tags --exact-match || echo "Not a tag"

      - name: Deploy to Aptible Staging
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          git_remote: primetime.aptible.com
          auth_root_url: https://auth.aptible.com
          api_root_url: https://api.aptible.com
          aptible_remote: aptible
