name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy (e.g. main, feature/my-branch, v1.2.3)"
        required: true
        default: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the specified ref
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.APTIBLE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan primetime.aptible.com >> ~/.ssh/known_hosts

      - name: Push tag commit to Aptible remote
        run: |
          export TEMP_BRANCH="deploy-${{ github.run_id }}"
          git remote add aptible ssh://git@primetime.aptible.com/illinois-get-childcare-staging.git
          git push aptible HEAD:refs/heads/$TEMP_BRANCH --force
          echo "temp_branch=$TEMP_BRANCH" >> $GITHUB_ENV

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          git_remote: primetime.aptible.com
          auth_root_url: https://auth.aptible.com
          api_root_url: https://api.aptible.com
          aptible_remote: aptible
