name: Deploy to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        default: 'v1.0.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Aptible CLI
        run: |
          curl -Lo aptible https://github.com/aptible/aptible-cli/releases/download/v0.16.4/aptible-linux-amd64
          chmod +x aptible
          sudo mv aptible /usr/local/bin/
          aptible version

      - name: Login to Aptible
        run: |
          aptible login --email ${{ secrets.APTIBLE_EMAIL }} --password ${{ secrets.APTIBLE_PASSWORD }} --environment illinois-staging

      - name: Deploy to Aptible
        run: |
          aptible deploy --app illinois-get-childcare-staging --environment illinois-staging --git-remote git@primetime.aptible.com:illinois-get-childcare-staging.git

      - name: Announce on Slack
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
