name: Deploy to Aptible Staging

on:
  workflow_dispatch:
    inputs: { }

jobs:
  deploy:
    name: Deploy to aptible-staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
      #         Looking for secrets/variables for the application? Check the configuration tab in the Aptible app GUI

      - name: Generate Sentry release name
        id: generate-release
        run: |
          # Remove refs/heads/ or refs/tags/ prefix and replace slashes with dashes
          REF_NAME=${GITHUB_REF#refs/*/}
          RELEASE_NAME=${REF_NAME//\//-}
          echo "RELEASE=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          release: ${{ env.RELEASE }}

      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
