name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true

jobs:
  deploy:
    name: Deploy Hotfix to Aptible Staging
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the tag AND fetch the main branch
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}
          # Fetch all branches so the action can push to main
          persist-credentials: true

      # 2. Fetch main explicitly to have it locally
      - name: Fetch main branch
        run: git fetch origin main:main

      # 3. Deploy to Aptible
      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}

      # 4. Generate Sentry release
      - name: Generate Sentry release
        run: echo "RELEASE=$(git rev-parse HEAD)" >> $GITHUB_ENV

      # 5. Create Sentry release
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          ignore_missing: true
          version: ${{ env.RELEASE }}

      # 6. Announce on Slack
      - name: Announce on Slack
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
