name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs: { }

jobs:
  deploy:
    name: Deploy Hotfix to Aptible Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}

      - name: Generate Sentry release name from ref
        id: generate-release
        run: |
          # Remove refs/heads/ or refs/tags/ prefix
          RELEASE_NAME=${GITHUB_REF#refs/heads/}
          RELEASE_NAME=${RELEASE_NAME#refs/tags/}
          # Replace slashes with dashes to satisfy Sentry
          RELEASE_NAME=${RELEASE_NAME//\//-}
          echo "RELEASE=$RELEASE_NAME" >> $GITHUB_ENV
          echo "Release name for Sentry: $RELEASE_NAME"

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          release: ${{ env.RELEASE }}
          ignore_missing: true

      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
