name: Deploy to AWS QA

on:
  workflow_run:
    workflows: [ "Run tests" ]
    types: [ completed ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: illinois-getchildcare-qa-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t illinois-getchildcare-qa-app --platform linux/amd64 .
          docker push 891377151751.dkr.ecr.us-east-1.amazonaws.com/illinois-getchildcare-qa-app:${{env.IMAGE_TAG}}

      - name: Update SSM Version Parameter
        run: |
          aws ssm put-parameter \
            --name /illinois-getchildcare/qa/version \
            --value ${{env.IMAGE_TAG}}

      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}