name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy (e.g. main, feature/my-branch, v1.2.3)"
        required: true
        default: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the requested ref
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      # 2. Install Aptible CLI globally and login
      - name: Install Aptible CLI and login
        run: |
          # Install Aptible CLI globally
          curl -sL https://cli.aptible.com/install.sh | sudo bash

          # Verify installation
          aptible version

          # Login to Aptible
          aptible login \
            --email "${{ secrets.APTIBLE_USERNAME }}" \
            --password "${{ secrets.APTIBLE_PASSWORD }}" \
            --environment illinois-staging

      # 3. Add Aptible remote
      - name: Add Aptible git remote
        run: git remote add aptible git@primetime.aptible.com:illinois-staging/illinois-get-childcare-staging.git

      # 4. Push the selected ref
      - name: Push selected ref to Aptible
        run: |
          REF="${{ github.event.inputs.ref }}"

          # Ensure the ref exists
          if ! git rev-parse "$REF" >/dev/null 2>&1; then
            echo "Ref $REF does not exist!"
            exit 1
          fi

          # Deploy tags as tags, branches to main
          if git show-ref --tags | grep -q "$REF"; then
            echo "Pushing tag $REF to Aptible..."
            git p
