name: Deploy Hotfix to Aptible Staging

# Keep this workflow only on `main`
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy (e.g. main, feature/my-branch, v1.2.3)"
        required: true
        default: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Login to Aptible
        run: |
          aptible login \
            --email "${{ secrets.APTIBLE_USERNAME }}" \
            --password "${{ secrets.APTIBLE_PASSWORD }}" \
            --environment illinois-staging

      - name: Add Aptible git remote
        run: git remote add aptible git@primetime.aptible.com:illinois-staging/illinois-get-childcare-staging.git

      - name: Push selected ref to Aptible
        run: git push aptible HEAD:refs/heads/main --force

      - name: Generate Sentry release name from sha
        run: echo "RELEASE=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          ignore_missing: true
          version: ${{ env.RELEASE }}

      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
