name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs: { }  

jobs:
  deploy:
    name: Deploy to aptible-staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}


      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          version: ${{ github.ref }}

      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
