name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        required: true
        default: ""

jobs:
  deploy:
    name: Deploy to Aptible Staging
    runs-on: ubuntu-latest
    steps:
      # Checkout the tag commit
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0
          fetch-tags: true

      # Generate a temporary branch name
      - name: Set temporary deploy branch
        id: temp_branch
        run: |
          echo "TEMP_BRANCH=deploy-$((RANDOM))" >> $GITHUB_ENV

      # Push the tag commit to Aptible as a temporary branch
      - name: Push tag commit to Aptible
        run: |
          git remote add aptible https://$APTIBLE_USERNAME:$APTIBLE_PASSWORD@primetime.aptible.com/illinois-staging/illinois-get-childcare-staging.git
          git push aptible HEAD:refs/heads/$TEMP_BRANCH --force
          echo "Pushed tag commit $GITHUB_SHA to temporary branch $TEMP_BRANCH"

      # Trigger Aptible deploy
      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          git_remote: primetime.aptible.com
          auth_root_url: https://auth.aptible.com
          api_root_url: https://api.aptible.com
          aptible_remote: aptible

      # Create Sentry release from the tag commit
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          version: ${{ github.event.inputs.tag }}
          ignore_missing: true

      # Notify Slack
      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
