name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (e.g., v1.2.3)'
        required: true

jobs:
  deploy:
    name: Deploy Hotfix to Aptible Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Push tag commit to temporary branch
        run: |
          TEMP_BRANCH="deploy-$RANDOM"
          git checkout -b $TEMP_BRANCH
          git remote add aptible https://${{ secrets.APTIBLE_USERNAME }}:${{ secrets.APTIBLE_PASSWORD }}@primetime.aptible.com/illinois-staging/illinois-get-childcare-staging.git
          git push aptible $TEMP_BRANCH --force
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV
          echo "Pushed tag commit $GITHUB_SHA to temporary branch $TEMP_BRANCH"

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          git_remote: primetime.aptible.com
          aptible_remote: aptible
          deploy_ref: ${{ env.TEMP_BRANCH }}

      - name: Generate Sentry release
        run: echo "RELEASE=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          version: ${{ env.RELEASE }}
          ignore_missing: true

      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
