name: Deploy Hotfix to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy (e.g. v1.2.3)"
        required: true

jobs:
  deploy:
    name: Deploy Hotfix to Aptible Staging
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the tag the user provides
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      # 2. Deploy the tag to Aptible using aptible-deploy-action
      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          deploy_ref: ${{ github.event.inputs.tag }}  # deploy tag as tag

      # 3. Generate Sentry release name from SHA
      - name: Generate Sentry release name from sha
        id: generate-release
        run: echo "RELEASE=$(git rev-parse HEAD)" >> $GITHUB_ENV

      # 4. Create Sentry release
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          ignore_missing: true
          version: ${{ env.RELEASE }}

      # 5. Announce on Slack
      - name: Announce on Slack
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
