name: Deploy to Aptible (any branch or tag)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy (e.g. main, feature/my-branch, v1.2.3)"
        required: true
        default: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          git_ref: ${{ github.event.inputs.ref }}   # <-- KEY FIX

      - name: Generate Sentry release name from sha
        run: echo "RELEASE=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          ignore_missing: true
          version: ${{ env.RELEASE }}

      - name: Announce on Slack when deployed
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
