name: Deploy to Aptible Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: false
        default: "main"

jobs:
  deploy:
    name: Deploy to Aptible Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@v5
        with:
          type: git
          app: illinois-get-childcare-staging
          environment: illinois-staging
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
      # Looking for secrets/variables for the application? Check the configuration tab in the Aptible app GUI

      - name: Generate Sentry release name from sha
        id: generate-release
        run: echo "RELEASE=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: codeforamerica
          SENTRY_PROJECT: il-gcc
        with:
          environment: staging
          ignore_missing: true
          release: ${{ steps.generate-release.outputs.RELEASE }}

      - name: Announce on Slack when deployed
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
